apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    traffic.sidecar.istio.io/excludeInboundPorts: 4444,4567,4568
    traffic.sidecar.istio.io/excludeOutboundPorts: 4444,4567,4568,443
    traffic.sidecar.istio.io/includeInboundPorts: '*'
  labels:
    app: mariadb-galera
    sidecar.istio.io/inject: 'false'
    version: 11.1.2
  name: mariadb-galera
  namespace: onap
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"onap-dcaegen2-services"},"name":"onap-dcae-ves-collector-read","namespace":"onap"}}

      '
  labels:
    app.kubernetes.io/instance: onap-dcaegen2-services
  name: onap-dcae-ves-collector-read
  namespace: onap
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"onap-policy"},"name":"onap-policy-apex-pdp-read","namespace":"onap"}}

      '
  labels:
    app.kubernetes.io/instance: onap-policy
  name: onap-policy-apex-pdp-read
  namespace: onap
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"onap-policy"},"name":"onap-policy-api-read","namespace":"onap"}}

      '
  labels:
    app.kubernetes.io/instance: onap-policy
  name: onap-policy-api-read
  namespace: onap
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"onap-policy"},"name":"onap-policy-clamp-ac-a1pms-ppnt-create","namespace":"onap"}}

      '
  labels:
    app.kubernetes.io/instance: onap-policy
  name: onap-policy-clamp-ac-a1pms-ppnt-create
  namespace: onap
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"onap-policy"},"name":"onap-policy-clamp-ac-http-ppnt-read","namespace":"onap"}}

      '
  labels:
    app.kubernetes.io/instance: onap-policy
  name: onap-policy-clamp-ac-http-ppnt-read
  namespace: onap
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"onap-policy"},"name":"onap-policy-clamp-ac-k8s-ppnt-create","namespace":"onap"}}

      '
  labels:
    app.kubernetes.io/instance: onap-policy
  name: onap-policy-clamp-ac-k8s-ppnt-create
  namespace: onap
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"onap-policy"},"name":"onap-policy-clamp-ac-kserve-ppnt-create","namespace":"onap"}}

      '
  labels:
    app.kubernetes.io/instance: onap-policy
  name: onap-policy-clamp-ac-kserve-ppnt-create
  namespace: onap
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"onap-policy"},"name":"onap-policy-clamp-ac-pf-ppnt-read","namespace":"onap"}}

      '
  labels:
    app.kubernetes.io/instance: onap-policy
  name: onap-policy-clamp-ac-pf-ppnt-read
  namespace: onap
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"onap-policy"},"name":"onap-policy-clamp-runtime-acm-read","namespace":"onap"}}

      '
  labels:
    app.kubernetes.io/instance: onap-policy
  name: onap-policy-clamp-runtime-acm-read
  namespace: onap
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"onap-policy"},"name":"onap-policy-pap-read","namespace":"onap"}}

      '
  labels:
    app.kubernetes.io/instance: onap-policy
  name: onap-policy-pap-read
  namespace: onap
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"onap-policy"},"name":"onap-policy-read","namespace":"onap"}}

      '
  labels:
    app.kubernetes.io/instance: onap-policy
  name: onap-policy-read
  namespace: onap
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"onap-sdnc"},"name":"onap-sdnc-ansible-server-read","namespace":"onap"}}

      '
  labels:
    app.kubernetes.io/instance: onap-sdnc
  name: onap-sdnc-ansible-server-read
  namespace: onap
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"onap-sdnc"},"name":"onap-sdnc-read","namespace":"onap"}}

      '
  labels:
    app.kubernetes.io/instance: onap-sdnc
  name: onap-sdnc-read
  namespace: onap
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"onap-sdnc"},"name":"onap-sdnc-web-read","namespace":"onap"}}

      '
  labels:
    app.kubernetes.io/instance: onap-sdnc
  name: onap-sdnc-web-read
  namespace: onap
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: onap-strimzi
    app.kubernetes.io/managed-by: strimzi-cluster-operator
    app.kubernetes.io/name: entity-operator
    app.kubernetes.io/part-of: strimzi-onap-strimzi
    strimzi.io/cluster: onap-strimzi
    strimzi.io/component-type: entity-operator
    strimzi.io/kind: Kafka
    strimzi.io/name: onap-strimzi-entity-operator
  name: onap-strimzi-entity-operator
  namespace: onap
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: onap-strimzi
    app.kubernetes.io/managed-by: strimzi-cluster-operator
    app.kubernetes.io/name: kafka
    app.kubernetes.io/part-of: strimzi-onap-strimzi
    strimzi.io/cluster: onap-strimzi
    strimzi.io/component-type: kafka
    strimzi.io/kind: Kafka
    strimzi.io/name: onap-strimzi-kafka
  name: onap-strimzi-kafka
  namespace: onap
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: strimzi-kafka
    app.kubernetes.io/instance: onap-strimzi-kafka
    app.kubernetes.io/managed-by: strimzi-cluster-operator
    app.kubernetes.io/name: kafka-bridge
    app.kubernetes.io/part-of: strimzi-onap-strimzi-kafka
    helm.sh/chart: strimzi-kafka-bridge-13.0.3
    strimzi.io/cluster: onap-strimzi-kafka
    strimzi.io/component-type: kafka-bridge
    strimzi.io/kind: KafkaBridge
    strimzi.io/name: onap-strimzi-kafka-bridge
    version: 13.0.3
  name: onap-strimzi-kafka-bridge
  namespace: onap
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"onap-strimzi"},"name":"onap-strimzi-kafka-read","namespace":"onap"}}

      '
  labels:
    app.kubernetes.io/instance: onap-strimzi
  name: onap-strimzi-kafka-read
  namespace: onap
