apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: onap-read-binding
  namespace: onap
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: onap-read
subjects:
- kind: ServiceAccount
  name: onap-policy-api-read
  namespace: onap
- kind: ServiceAccount
  name: onap-policy-pap-read
  namespace: onap
- kind: ServiceAccount
  name: onap-policy-clamp-runtime-acm-read
  namespace: onap
- kind: ServiceAccount
  name: onap-policy-apex-pdp-read
  namespace: onap
- kind: ServiceAccount
  name: onap-sdnc-read
  namespace: onap
- kind: ServiceAccount
  name: onap-sdnc-ansible-server-read
  namespace: onap
- kind: ServiceAccount
  name: onap-sdnc-web-read
  namespace: onap
