apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '-3'
  name: onap-policy-api-read
  namespace: onap
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onap-policy-pap-read
  namespace: onap
  annotations:
    argocd.argoproj.io/sync-wave: '-3'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onap-policy-clamp-runtime-acm-read
  namespace: onap
  annotations:
    argocd.argoproj.io/sync-wave: '-3'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onap-policy-clamp-ac-k8s-ppnt-create
  namespace: onap
  annotations:
    argocd.argoproj.io/sync-wave: '-3'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onap-policy-clamp-ac-http-ppnt-read
  namespace: onap
  annotations:
    argocd.argoproj.io/sync-wave: '-3'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onap-policy-clamp-ac-a1pms-ppnt-create
  namespace: onap
  annotations:
    argocd.argoproj.io/sync-wave: '-3'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onap-policy-apex-pdp-read
  namespace: onap
  annotations:
    argocd.argoproj.io/sync-wave: '-3'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onap-policy-clamp-ac-pf-ppnt-read
  namespace: onap
  annotations:
    argocd.argoproj.io/sync-wave: '-3'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onap-sdnc-read
  namespace: onap
  annotations:
    argocd.argoproj.io/sync-wave: '-3'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onap-sdnc-ansible-server-read
  namespace: onap
  annotations:
    argocd.argoproj.io/sync-wave: '-3'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onap-sdnc-web-read
  namespace: onap
  annotations:
    argocd.argoproj.io/sync-wave: '-3'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mariadb-galera
  namespace: onap
  annotations:
    argocd.argoproj.io/sync-wave: '-3'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onap-strimzi-kafka-bridge
  namespace: onap
  annotations:
    argocd.argoproj.io/sync-wave: '-3'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onap-strimzi-entity-operator
  namespace: onap
  annotations:
    argocd.argoproj.io/sync-wave: '-3'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: strimzi-cluster-operator
  namespace: strimzi-system
  annotations:
    argocd.argoproj.io/sync-wave: '-3'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onap-dcae-ves-collector-read
  namespace: onap
  annotations:
    argocd.argoproj.io/sync-wave: '-3'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onap-policy-clamp-ac-kserve-ppnt-create
  namespace: onap
  annotations:
    argocd.argoproj.io/sync-wave: '-3'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onap-policy-read
  namespace: onap
  annotations:
    argocd.argoproj.io/sync-wave: '-3'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onap-strimzi-kafka
  namespace: onap
  annotations:
    argocd.argoproj.io/sync-wave: '-3'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onap-strimzi-kafka-read
  namespace: onap
  annotations:
    argocd.argoproj.io/sync-wave: '-3'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: onap-read
  namespace: onap
  annotations:
    argocd.argoproj.io/sync-wave: '-3'
rules:
- apiGroups:
  - ''
  - apps
  resources:
  - services
  - endpoints
  - pods
  - configmaps
  - secrets
  - replicasets
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: onap-read-binding
  namespace: onap
  annotations:
    argocd.argoproj.io/sync-wave: '-3'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: onap-read
subjects:
- kind: ServiceAccount
  name: onap-policy-api-read
  namespace: onap
- kind: ServiceAccount
  name: onap-policy-pap-read
  namespace: onap
- kind: ServiceAccount
  name: onap-policy-clamp-runtime-acm-read
  namespace: onap
- kind: ServiceAccount
  name: onap-policy-clamp-ac-k8s-ppnt-create
  namespace: onap
- kind: ServiceAccount
  name: onap-policy-clamp-ac-http-ppnt-read
  namespace: onap
- kind: ServiceAccount
  name: onap-policy-clamp-ac-a1pms-ppnt-create
  namespace: onap
- kind: ServiceAccount
  name: onap-policy-apex-pdp-read
  namespace: onap
- kind: ServiceAccount
  name: onap-policy-clamp-ac-pf-ppnt-read
  namespace: onap
- kind: ServiceAccount
  name: onap-sdnc-read
  namespace: onap
- kind: ServiceAccount
  name: onap-sdnc-ansible-server-read
  namespace: onap
- kind: ServiceAccount
  name: onap-sdnc-web-read
  namespace: onap
- kind: ServiceAccount
  name: mariadb-galera
  namespace: onap
- kind: ServiceAccount
  name: onap-strimzi-kafka
  namespace: onap
- kind: ServiceAccount
  name: onap-strimzi-kafka-bridge
  namespace: onap
- kind: ServiceAccount
  name: onap-strimzi-entity-operator
  namespace: onap
- kind: ServiceAccount
  name: onap-dcae-ves-collector-read
  namespace: onap
- kind: ServiceAccount
  name: onap-policy-clamp-ac-kserve-ppnt-create
  namespace: onap
- kind: ServiceAccount
  name: onap-policy-read
  namespace: onap
- kind: ServiceAccount
  name: onap-strimzi-kafka-read
  namespace: onap
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: onap-strimzi-kafka-broker
  annotations:
    argocd.argoproj.io/sync-wave: '-3'
rules:
- apiGroups:
  - ''
  resources:
  - nodes
  - pods
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: onap-strimzi-kafka-broker-binding
  annotations:
    argocd.argoproj.io/sync-wave: '-3'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: onap-strimzi-kafka-broker
subjects:
- kind: ServiceAccount
  name: onap-strimzi-kafka
  namespace: onap
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: strimzi-cluster-operator-global-system
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: strimzi-cluster-operator-global
subjects:
- kind: ServiceAccount
  name: strimzi-cluster-operator
  namespace: strimzi-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: strimzi-cluster-operator-leader-election
  namespace: strimzi-system
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: strimzi-cluster-operator-leader-election
subjects:
- kind: ServiceAccount
  name: strimzi-cluster-operator
  namespace: strimzi-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: strimzi-cluster-operator-namespaced
  namespace: strimzi-system
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: strimzi-cluster-operator-namespaced
subjects:
- kind: ServiceAccount
  name: strimzi-cluster-operator
  namespace: strimzi-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: strimzi-cluster-operator-kafka-broker-delegation-system
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: strimzi-kafka-broker
subjects:
- kind: ServiceAccount
  name: strimzi-cluster-operator
  namespace: strimzi-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: strimzi-cluster-operator-leader-election
  labels:
    app: strimzi
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - watch
  - delete
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: strimzi-cluster-operator-custom-global
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
rules:
- apiGroups:
  - kafka.strimzi.io
  resources:
  - kafkas
  - kafkaconnects
  - kafkaconnectors
  - kafkamirrormaker2s
  - kafkabridges
  - kafkarebalances
  - kafkatopics
  - kafkausers
  - kafkanodepools
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups:
  - core.strimzi.io
  resources:
  - strimzipodsets
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - configmaps
  - secrets
  - persistentvolumeclaims
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - clusterrolebindings
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: strimzi-cluster-operator-custom-global-binding
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: strimzi-cluster-operator-custom-global
subjects:
- kind: ServiceAccount
  name: strimzi-cluster-operator
  namespace: strimzi-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: strimzi-cluster-operator-global
  labels:
    app: strimzi
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
rules:
- apiGroups:
  - kafka.strimzi.io
  resources:
  - kafkas
  - kafkaconnects
  - kafkaconnectors
  - kafkamirrormaker2s
  - kafkabridges
  - kafkarebalances
  - kafkatopics
  - kafkausers
  - kafkanodepools
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups:
  - kafka.strimzi.io
  resources:
  - kafkas/status
  - kafkaconnects/status
  - kafkaconnectors/status
  - kafkamirrormaker2s/status
  - kafkabridges/status
  - kafkarebalances/status
  - kafkatopics/status
  - kafkausers/status
  - kafkanodepools/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.strimzi.io
  resources:
  - strimzipodsets
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups:
  - core.strimzi.io
  resources:
  - strimzipodsets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - configmaps
  - secrets
  - persistentvolumeclaims
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - clusterrolebindings
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: strimzi-kafka-broker
  labels:
    app: strimzi
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
