apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: onap-sdnc
  namespace: argocd
spec:
  destination:
    namespace: onap
    server: https://kubernetes.default.svc
  project: default
  sources:
  - chart: sdnc
    helm:
      ignoreMissingValueFiles: true
      values: "cds:\n  enabled: false\nconfig:\n  sdnr:\n    enabled: true\n    kafka:\n\
        \      enabled: true\n    mariadb:\n      enabled: true\n    mode: dm\n  \
        \  mountpointRegistrarEnabled: true\n    mountpointStateProviderEnabled: true\n\
        \    netconfCallHome:\n      enabled: true\n    sdnrdbTrustAllCerts: true\n\
        \    sdnronly: true\ndgbuilder:\n  enabled: false\nelasticsearch:\n  enabled:\
        \ false\nenabled: true\nglobal:\n  addTestingComponents: true\n  cmpv2Enabled:\
        \ false\n  debugEnabled: false\n  dockerHubRepository: nexus3.onap.org:10001\n\
        \  flavor: unlimited\n  imageRegistry: nexus3.onap.org:10001\n  ingress:\n\
        \    enabled: false\n    provider: ingress\n  loggingRepository: docker.elastic.co\n\
        \  mariadbGalera:\n    enableServiceAccount: false\n    useOperator: true\n\
        \  masterPassword: secretpassword\n  nodePortPrefix: 302\n  nodePortPrefixExt:\
        \ 304\n  persistence:\n    mountPath: /dockerdata-nfs\n    storageClass: smo-storage\n\
        \  prometheusEnabled: false\n  pullPolicy: IfNotPresent\n  readinessRepository:\
        \ oomk8s\n  repository: nexus3.onap.org:10001\nimage: onap/sdnc-image:2.6.1\n\
        mysql:\n  replicaCount: 1\nnetwork-name-gen:\n  enabled: false\nreplicaCount:\
        \ 1\nsdnc-ansible-server:\n  enabled: true\n  image: onap/sdnc-ansible-server-image:2.6.1\n\
        sdnc-web:\n  image: onap/sdnc-web-image:2.6.1\nueb-listener:\n  enabled: false\n\
        \  image: onap/sdnc-ueb-listener-image:2.6.1\n"
    repoURL: http://chartmuseum.chartmuseum.svc.cluster.local:8080
    targetRevision: '*'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
    syncOptions:
    - CreateNamespace=true
