apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"onap-sdnc"},"name":"onap-sdnc-read","namespace":"onap"}}
    creationTimestamp: "2026-01-23T10:59:18Z"
    labels:
      app.kubernetes.io/instance: onap-sdnc
    name: onap-sdnc-read
    namespace: onap
    resourceVersion: "1231866"
    uid: 1802f468-e644-4f46-ac7c-b0d27d599bc7
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"onap-sdnc"},"name":"onap-sdnc-web-read","namespace":"onap"}}
    creationTimestamp: "2026-01-23T10:59:23Z"
    labels:
      app.kubernetes.io/instance: onap-sdnc
    name: onap-sdnc-web-read
    namespace: onap
    resourceVersion: "1231864"
    uid: 375302ae-9dd7-45f8-8b54-b5dd1860a5dd
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"onap-sdnc"},"name":"onap-sdnc-ansible-server-read","namespace":"onap"}}
    creationTimestamp: "2026-01-23T10:59:20Z"
    labels:
      app.kubernetes.io/instance: onap-sdnc
    name: onap-sdnc-ansible-server-read
    namespace: onap
    resourceVersion: "1231865"
    uid: 8f496e21-17de-4413-b937-e32f1db8c0c6
kind: List
metadata:
  resourceVersion: ""
